name: CI/CD for Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.hvmnn }}
          password: ${{ secrets.ghostrider1571 }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.hvmnn }}/taller3backend-arqui:latest .

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.hvmnn }}/taller3backend-arqui:latest

      - name: Trigger Render Webhook
        run: |
          curl -X POST ${{ secrets.RENDER_WEBHOOK }}
